### ISSUE TITLE
Wait for qBittorrent to become ready while starting

### ISSUE THREAD

**Issue by mat926** [claabs/qBittorrent-PIA-Port-Forwarder#2]
My qBittorrent container takes a while to initialize before the Web UI becomes available.   I will get errors like `curl: (56) Recv failure: Connection reset by peer` while qBit is starting. 

Here's my docker compose file

```
  qbittorrent-port:
    image: charlocharlie/qbittorrent-port-forward-file:latest
    container_name: qbittorrent-port
    environment:
      - PUID=1027
      - PGID=65536
      - QBT_USERNAME=***
      - QBT_PASSWORD=***
      - QBT_ADDR=http://192.168.0.143:8090
      - PORT_FILE=/config/forwarded_port.txt
    volumes:
      - /volume1/docker/gluetun:/config:ro
    restart: unless-stopped  
    network_mode: gluetun
    depends_on:
       gluetun:
         condition: service_healthy
       qbittorrent:
         condition: service_started

```

I have the 2 depends_on conditions for gluetun and qbit. Since qbit doesn't have a health check in the pod, I used service_started.  Is there a way to wait until Web UI is available?
